import { Dimensions, StyleSheet } from 'react-native';
import { red } from 'react-native-reanimated/lib/typescript/Colors';

const screenWidth = Dimensions.get('window').width;

export const styles = StyleSheet.create({
    scrollView: {
        flex: 1,
        backgroundColor: '#000000',
    },
    scrollContent: {
        paddingTop: 110,
        flexGrow: 1,
        justifyContent: 'flex-start',
        alignItems: 'center',
    },
    container: {
        height: '100%',
        width: '100%',
        alignItems: 'flex-start',
        justifyContent: 'flex-start',
        
    },
    containerCenter: {
        width: screenWidth * 1,
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingVertical: 20,
        paddingHorizontal: screenWidth * 0.05,
        borderRadius: 50,
        
        alignSelf: 'center',
    },
    containerLeft: {
        marginTop: 20,
        height: '100%',
        alignItems: 'flex-start',
        justifyContent: 'flex-start',
    },
    
    containerSearch:{
        width: '100%',
        margin: 0,
        
        justifyContent: 'center',
    },
    containerHorizontal: {
        flexDirection: 'row',
        alignItems: 'center',
        width: '90%',
        borderRadius: 25,
    },
    containerHorizontalPassword: {
        display: 'flex',
        flexDirection: 'row',
        alignItems: 'center',
        width: '100%',
        marginBottom: 5,
        gap: 11,
        borderRadius: 25,
    },
    containerGenerate:{
        display: 'flex',
        flexDirection: 'row',
        alignItems: 'center',
        paddingBottom: 5,
        gap: 25,
    },
    
    text: {
        fontSize: 20,
        fontWeight: 'bold',
        margin: 10,
        color: 'black',
    },
    textWhite: {
        fontSize: 20,
        fontWeight: 'bold',
        margin: 10,
       
        color: 'white',
    },
    textWhite2: {
        fontSize: 20,
        fontWeight: 'bold',
        marginTop: -10,
        marginLeft: -5,
        marginBottom: 5,
        color: 'white',
    },

    textWhiteVault: {
        fontSize: 20,
        marginBottom: 5,
        fontWeight: 'bold',
        color: 'white',
    },
    textWelcome: {
        fontSize: 20,
        fontWeight: 'bold',
        margin: 10,
        marginBottom: 2,
        color: 'white',
        textAlign: 'left',
    },
    textWelcomeSubtitle: {
        fontSize: 16,
        margin: 10,
        marginTop: 2,
        color: 'white',
        textAlign: 'left',
    },
    /* Eto yung welcome to cybervault */
    capsule: {
        width: screenWidth * 0.9,
        backgroundColor: '#111827',
        paddingVertical: 5,
        paddingHorizontal: screenWidth * 0.08,
        borderRadius:20,
        alignSelf: 'center',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.25,
        shadowRadius: 3.5,
        elevation: 5,
        alignItems: 'flex-start',
        paddingLeft: 5, 
    },
    capsuleContainerCenter: {
        width: screenWidth * 0.9,
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingVertical: 10,
        borderRadius: 50,
        alignSelf: 'center',
    },
    capsuleCenter: {
        width: screenWidth * 0.9,
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingHorizontal: screenWidth * 0.05,
        borderRadius: 50,
        alignSelf: 'center',
        gap: 5,
        
    },
    capsuleCenter2: {
        width: screenWidth * 0.9,
        flexDirection: 'row',
        flexWrap: 'wrap',
        justifyContent: 'space-between',
        alignItems: 'center',
        borderRadius: 50,
        alignSelf: 'center',
        gap: 6,
    },
    /* Core features, Vault Logo(2nd Page) */
    capsuleChild2:{
        width: '100%',
        height: 90,
        backgroundColor: '#111827',
        paddingVertical: 10,
        paddingHorizontal: 20,
        alignItems: 'center',
        borderRadius: 20,
        flexDirection: 'row',
        gap: 10,
        shadowColor: '#000000',
        shadowOffset: { width: 0, height: 5 },
        shadowOpacity: 0.25,
        shadowRadius: 3.5,
        elevation: 5,
    }, 
     contentChildImage:{
        display: 'flex',
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#078080ff',
        width: '100%',
        height: '100%',
        borderRadius: 15,
        padding: 10,
        gap: 10,
    },
    contentChildVideo:{
        display: 'flex',
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#0b9c90ff',
        width: '100%',
        height: '100%',
        borderRadius: 15,
        padding: 10,
        gap: 10,
    },
    contentChildAddImage:{
        display: 'flex',
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#1b82bdff',
        width: '100%',
        height: '100%',
        borderRadius: 15,
        padding: 10,
        gap: 10,
    },
    contentChildAddVideo:{
        display: 'flex',
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#1E90FF',
        width: '100%',
        height: '100%',
        borderRadius: 15,
        padding: 10,
        gap: 10,
    },

    
    capsuleContainerLeft: {
        width: screenWidth * 1,
        flexDirection: 'column',
        justifyContent: 'space-between',
        paddingVertical: 5,
        paddingHorizontal: screenWidth * 0.05,
        borderRadius: 50,
        alignSelf: 'center',
    },

    /* Media Vault (2nd page) */
    capsuleContainerLeftVault: {
        width: screenWidth * 1,
        flexDirection: 'column',
        justifyContent: 'space-between',
        paddingVertical: 5,
        paddingHorizontal: screenWidth * 0.05,
        borderRadius: 50,
        alignSelf: 'center',
    },
    capsuleChildDocument: {
        width: screenWidth * 0.43,
        backgroundColor: 'background-color: rgba(188, 19, 254, 0.15);',
        paddingVertical: 20,
        borderRadius: 20,
        alignItems: 'center',
        justifyContent: 'center',
        shadowColor: '#000000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.25,
        shadowRadius: 3.5,
        
    },
    capsuleChildKey: {
        width: screenWidth * 0.43,
        backgroundColor: 'background-color: rgba(57, 255, 20, 0.15);',
        paddingVertical: 20,
        borderRadius: 20,
        alignItems: 'center',
        justifyContent: 'center',
        shadowColor: '#000000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.25,
        shadowRadius: 3.5,
        
    },
    

    capsuleChild: {
        width: screenWidth * 0.29,
        backgroundColor: '#111827',
        paddingVertical: 20,
        borderRadius: 20,
        alignItems: 'center',
        justifyContent: 'center',
        shadowColor: '#000000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.25,
        shadowRadius: 3.5,
        elevation: 5,
    },
    capsuleContainerCenterBreaches: {
        width: screenWidth * 0.9,
        backgroundColor: '#111827',
        flexDirection: 'row',
        gap: 10,
        marginTop: 5,
        alignItems: 'center',
        paddingVertical: 5,
        borderRadius: 16,
        alignSelf: 'center',
    },
    capsuleChildBreaches: {
        width: 40,
        flexDirection: 'column',
        backgroundColor: 'background-color: rgba(255, 7, 58, 0.15);',
        borderRadius: 16,
        alignItems: 'center',
        justifyContent: 'flex-start',
        gap: 1,
        marginLeft: 5,
        shadowColor: '#000000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.25,
        shadowRadius: 3.5,
        elevation: 5,
        
    },
    capsuleContainerCenterPassword: {
        width: screenWidth * 0.9,
        backgroundColor: '#111827',
        flexDirection: 'row',
        gap: 10,
        marginTop: 5,
        alignItems: 'center',
        paddingVertical: 5,
        borderRadius: 16,
        alignSelf: 'center',
    },
    capsuleChildPassword: {
        width: 40,
        
        flexDirection: 'column',
        backgroundColor: 'background-color: rgba(57, 255, 20, 0.15);',
        
        borderRadius: 16,
        alignItems: 'center',
        justifyContent: 'flex-start',
        gap: 1,
        marginLeft: 5,
        shadowColor: '#000000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.25,
        shadowRadius: 3.5,
        elevation: 5,
    },
    titlePassword: {
        fontSize: 22,
        fontWeight: 'bold',
        color: '#39FF14',
        textAlign: 'left',
        
        marginBottom: 8,
        
    },
    titleBreaches: {
        fontSize: 22,
        fontWeight: 'bold',
        color: '#FF073A',
        textAlign: 'left',
        
        marginBottom: 8,
        
    },
    
    titleStored: {
        display: 'flex',
        flexDirection: 'row',
        gap: 5,
    },
    
    subtitlePassword: {
        fontSize: 20,
        
        fontWeight: 'bold',
        color: 'white',
        textAlign: 'center',
        marginTop: 2,
    },
   
    
    /* Core Features First Page */
    vaultCard: {
        flexDirection: 'row',
        textAlign: 'left',
        width: screenWidth * 0.9 ,
        backgroundColor: '#111827',
        paddingVertical: 20,
        borderRadius: 20,
        paddingLeft: 20,
        marginBottom: 8,
        shadowColor: '#000000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.25,
        shadowRadius: 3.5,
        elevation: 5,
    },
    iconDocument: {
        width: 80,
        height: 80,
        borderRadius: 16,
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: 12,
        backgroundColor: 'background-color: rgba(188, 19, 254, 0.15);',
    },
    iconKey: {
        width: 80,
        height: 80,
        borderRadius: 16,
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: 12,
        backgroundColor: 'background-color: rgba(57, 255, 20, 0.15);',
    },
    iconBreach: {
        width: 80,
        height: 80,
        borderRadius: 16,
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: 12,
        backgroundColor: 'background-color: rgba(255, 7, 58, 0.15);',
    },
    textContainer:{
        flex: 1,
        flexDirection: 'column',
        justifyContent: 'center',
        alignItems: 'flex-start',   
    },
     title: {
        fontSize: 22,
        fontWeight: 'bold',
        color: 'white',
        textAlign: 'left',
        marginBottom: 8,
    },
    titleCritical: {
        fontSize: 22,
        fontWeight: 'bold',
        color: '#f10b0b71',
        textAlign: 'left',
        marginBottom: 8,
    },
    titleHigh: {
        fontSize: 22,
        fontWeight: 'bold',
        color: '#eeae3780',
        textAlign: 'left',
        marginBottom: 8,
    },
    subtitle: {
        fontSize: 12,
        fontWeight: 'bold',
        color: 'white',
        textAlign: 'left',
        marginTop: 2,
    },
    subtitleCritical: {
        color: '#f10b0bff',
    },
    subtitleHigh: {
        color: '#eeae37ff',
    },
    capsuleChildLeft: {
        width: screenWidth * 0.9 ,
        backgroundColor: '#111827',
        paddingVertical: 20,
        borderRadius: 20,
        paddingLeft: 20,
        marginBottom: 8,
        alignItems: 'flex-start',
        justifyContent: 'center',
        shadowColor: '#000000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.25,
        shadowRadius: 3.5,
        elevation: 5,
    },
   
    safeArea: {
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        zIndex: 999,
        elevation: 10,
        backgroundColor: 'black',
        paddingTop: 0,
        
    },
    containerRibbon: {
        flexDirection: 'row',
        alignItems: 'center',
        
        paddingHorizontal: 18,
        gap: 20,
        backgroundColor: '#111827',
        height: 120,
    },
    documentIcon: {
        width: 65,
        height: 65,
        borderRadius: 25,
        backgroundColor: 'background-color: rgba(188, 19, 254, 0.15);',
        justifyContent: 'center',
        alignItems: 'center',
        padding: 4, 
    },
     documentIconVault: {
        width: 90,
        height: 85,
        borderRadius: 16,
        backgroundColor: '#BC13FE',
        justifyContent: 'center',
        alignItems: 'center',
        padding: 4, 
    },
    keyIconVault: {
        width: 90,
        height: 85,
        borderRadius: 16,
        backgroundColor: '#39FF14',
        justifyContent: 'center',
        alignItems: 'center',
        padding: 4, 
    },
    breachIconVault: {
        width: 65,
        height: 65,
        borderRadius: 16,
        backgroundColor: '#FF073A',
        justifyContent: 'center',
        alignItems: 'center',
        padding: 4, 
    },
    keyIcon: {
        width: 65,
        height: 65,
        borderRadius: 25,
        backgroundColor: 'background-color: rgba(57, 255, 20, 0.15);',
        justifyContent: 'center',
        alignItems: 'center',
        padding: 4, 
    },
    documentIconKey: {
        width: 65,
        height: 65,
        borderRadius: 16,
        backgroundColor: 'background-color: rgba(57, 255, 20, 0.15);',
        justifyContent: 'center',
        alignItems: 'center',
        padding: 4, 
    },
    breachIcon: {
        width: 65,
        height: 65,
        borderRadius: 25,
        backgroundColor: 'background-color: rgba(255, 7, 58, 0.15);',
        justifyContent: 'center',
        alignItems: 'center',
        padding: 4, 
    },
    iconShroud: {
        width: 48,
        height: 48,
        borderRadius: 32,
        backgroundColor: 'rgba(173, 174, 177, 0.2)',
        justifyContent: 'center',
        alignItems: 'center',
        padding: 4, 
    },
    iconShroudIsolated: {
        width: 48,
        height: 48,
        borderRadius: 32,
        backgroundColor: 'rgba(7, 72, 177, 1)',
        justifyContent: 'center',
        alignItems: 'center',
        padding: 4, 
    },
    iconTopRight: {
        position: 'absolute',
        top: 10,
        right: 10,
        borderRadius: 16,
        backgroundColor: 'rgba(175, 173, 177, 0.2)',
    },
    textStack: {
        flexDirection: 'column',
        justifyContent: 'center',
    },
    titleLeft: {
        fontSize: 35,
        fontWeight: 'bold',
        color: 'white',
        textAlign: 'left',
    },
    subtitleLeft: {
        fontSize: 12,
        fontWeight: 'bold',
        color: 'gray',
        textAlign: 'left',
        marginTop: 4,
    },
    titleRibbon: {
        fontSize: 22,
        fontWeight: 'bold',
        color: 'black',
        textAlign: 'left',
    },
    titleRibbonGenerate: {
        fontSize: 17,
        fontWeight: 'bold',
        color: 'black',
        textAlign: 'left',
    },
    subtitleRibbon: {
        fontSize: 16,
        fontWeight: 'bold',
        color: 'white',
        marginTop: 4,
    },
    subtitleBlack: {
        fontSize: 16,
        fontWeight: 'bold',
        color: 'grey',
        marginBottom: 2,
    },
    subtitleCategory: {
        fontSize: 16,
        fontWeight: 'bold',
        color: 'grey',
        marginBottom: 5,
    },
    modalOverlay: {
        flex: 1,
        backgroundColor: 'rgba(0,0,0,0.5)',
        justifyContent: 'center',
        alignItems: 'center',
    },
    modalContent: {
        width: '80%',
        maxHeight: '80%',
        padding: 20,
        backgroundColor: 'white',
        borderRadius: 12,
        alignItems: 'center',
    },
    modalOverlayTouchableArea: {
        position: 'absolute',
        top: 0,
        bottom: 0,
        left: 0,
        right: 0,
    },
    image: {
        width: 150,
        height: 150,
        margin: 5,
        borderRadius: 10,
    },
    imageBig: {
        width: '100%',
        height: '100%',
        borderRadius: 10,
    },
    imagesContainer: {
        height: 300,
        marginTop: 10,
        borderWidth: 1,
        borderColor: '#ccc',
        borderRadius: 12,
    },
    imagesInnerContainer: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        justifyContent: 'center',
        gap: 10,
    },
    fileButton: {
        backgroundColor: '#2563EB', 
        borderRadius: 10,
        paddingVertical: 10,
        alignSelf: 'center',
        width: 200,
        height: 45,
        alignItems: 'center',
        justifyContent: 'center',
        shadowColor: '#2563EB',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.4,
        shadowRadius: 10,
        elevation: 5,
        flexDirection: 'row',
    },
    generateButton: {
        backgroundColor: 'blue', 
        borderRadius: 10,
        paddingVertical: 10,
        width: 90,
        height: 40,
        alignItems: 'center',
        justifyContent: 'center',
        shadowColor: '#2563EB',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.4,
        shadowRadius: 10,
        elevation: 5,
        flexDirection: 'row',
    },
    numberButton: {
        backgroundColor: 'green',
        shadowColor: '#2563EB',
    },
    letterButton:{
        backgroundColor: 'green',
    },
    symbolButton:{
        backgroundColor: 'green',
    },
    numberButtonActive: {
        backgroundColor: '#16A34A', 
        shadowColor: '#22C55E',
    },
    numberButtonInactive: {
        backgroundColor: 'red', 
        opacity: 0.7,
    },
    letterButtonActive: {
        backgroundColor: '#16A34A', 
        shadowColor: '#22C55E',
    },
    letterButtonInactive: {
        backgroundColor: 'red', 
        opacity: 0.7,
    },
    symbolButtonActive: {
        backgroundColor: '#16A34A', 
        shadowColor: '#22C55E',
    },
    symbolButtonInactive: {
        backgroundColor: 'red', 
        opacity: 0.7,
    },
    blackButton: {
        backgroundColor: 'blue',
        shadowColor: '#2563EB',
        borderRadius: 10,
        paddingVertical: 10,
        alignSelf: 'center',
        width: 100,
        height: 40,
        alignItems: 'center',
        justifyContent: 'center',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.4,
        shadowRadius: 10,
        elevation: 5,
        flexDirection: 'row',
    },
    uploadButton: {
        backgroundColor: 'blue',
        shadowColor: '#2563EB',
        borderRadius: 10,
        paddingVertical: 10,
        alignSelf: 'flex-end',
        width: 100,
        height: 40,
        alignItems: 'center',
        justifyContent: 'center',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.4,
        shadowRadius: 10,
        elevation: 5,
        flexDirection: 'row',
        marginTop: 5,
    },
    searchButton: {
        backgroundColor: 'transparent',
        borderRadius: 10,
        paddingVertical: 10,
        alignSelf: 'center',
        alignItems: 'center',
        justifyContent: 'center',
        flexDirection: 'row',
        
    },
    flexButton: {
               
        
        borderRadius: 10,
        paddingVertical: 10,
        alignSelf: 'center',
        width: 90,
        height: 40,
        alignItems: 'center',
        justifyContent: 'center',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.4,
        shadowRadius: 10,
        elevation: 5,
        
    },
    buttonNumbers: {
        backgroundColor: 'green', 
        borderRadius: 10,
        paddingVertical: 10,
        alignSelf: 'center',
        width: 100,
        height: 30,
        alignItems: 'center',
        justifyContent: 'center',
        shadowColor: '#2563EB',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.4,
        shadowRadius: 10,
        elevation: 5,
        flexDirection: 'row',
    },
    blackButtonText: {
        color: 'white',
        fontSize: 16,
        fontWeight: 'bold',
    },
    closeButton:{
        backgroundColor: 'red',
        width: 100,
        height: 10,
    },
    redButton: {
        backgroundColor: '#FF3B30', 
        borderRadius: 10,           
        paddingVertical: 10,
        alignSelf: 'flex-end',
        width: 100,
        height: 45,
        alignItems: 'center',       
        justifyContent: 'center',  
        shadowColor: '#FF3B30',    
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.5,
        shadowRadius: 10,
        elevation: 5,         
        flexDirection: 'row',   
    },
    redButtonText: {
        color: 'white',
        fontSize: 16,
        fontWeight: '600',
        textAlign: 'center',
        textAlignVertical: 'center',
    },
    containerPhoto:{
        marginBottom: 40,
    },
    blackButtonTextSmall: {
        color: 'white',
        fontSize: 12,
        fontWeight: 'bold',
        
    },
    saveButton: {
        backgroundColor: '#2563EB', 
        borderRadius: 10,
        paddingVertical: 10,
        marginTop: 10,
        width: 100,
        height: 40,
        alignSelf: 'flex-end',
        alignItems: 'center',
        justifyContent: 'center',
        shadowColor: '#2563EB',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.4,
        shadowRadius: 10,
        elevation: 5,
        flexDirection: 'row',
    },
    
    searchContainer: {
        marginTop: 10,
        alignSelf: 'center',
        alignItems: 'center',
        paddingVertical: 5,
        width: '100%',
        marginBottom: 10,
        position: 'relative',
        
    },
    containerCategory:{
        
        alignSelf: 'center',
        justifyContent: 'center',
        alignItems: 'center',
        margin: 0,
        width: '100%',
        
    },
     searchInput: {
        width: '90%',
        alignSelf: 'center',
        color: '#fff',
        fontSize: 16,
        borderRadius: 32,
        backgroundColor: '#111827',
        paddingVertical: 10,
        paddingLeft: 45, 
        paddingRight: 15,
        
    },
    searchIcon: {
        position: 'absolute',
        left: 35,
        top: '40%',
        transform: [{ translateY: -4 }], 
        zIndex: 1,
        },
    searchInputContainer: {
        display: 'flex',
        flexDirection: 'row',
    },
    scrollViewHorizontal: {
        paddingHorizontal: 3,
        
    },
    categoryButton: {
        backgroundColor: '#111827',
        paddingVertical: 10,
        paddingHorizontal: 15,
        borderRadius: 25,
        marginRight: 10,
        alignItems: 'center',
        justifyContent: 'center',
    },
    input: {
        borderWidth: 1,
        borderColor: '#111827',
        borderRadius: 10,
        paddingVertical: 10,
        paddingHorizontal: 12,
        marginVertical: 8,
        fontSize: 16,
        backgroundColor: '#fff',
    },
    inputSearch: {
        borderWidth: 1,
        width: '90%',
        height: 40,
        borderColor: '#111827',
        borderRadius: 10,
        paddingVertical: 10,
        paddingHorizontal: 12,
        marginVertical: 8,
        fontSize: 16,
        backgroundColor: '#fff',
    },
    inputDisabled: {
        backgroundColor: '#333',
        color: '#fff',
        padding: 10,
        borderRadius: 8,
        marginVertical: 5,
        width: '100%',
        textAlign: 'center',
    },
    label: {
        fontSize: 16,
        marginBottom: 8,
        color: '#333',
    },
    pickerContainer: {
        borderWidth: 1,
        borderColor: '#999',
        borderRadius: 8,
        backgroundColor: '#222', // dark style
        overflow: 'hidden',
    },
    picker: {
        height: 50,
        alignItems: 'center',
        backgroundColor: 'white',
        color: 'black', 
    },
    selectedText: {
        marginTop: 12,
        fontSize: 14,
        color: '#555',
    },
    passwordGridContainer: {
        flex: 1,
        width: '100%',
        alignItems: 'center',
        justifyContent: 'flex-start',
        marginTop: 10,
        marginBottom: 40,
    },
    passwordGrid: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        justifyContent: 'center',
        alignItems: 'flex-start',
        width: '100%',
        paddingHorizontal: 10,
    },
    passwordCard: {
        width: '45%',
        backgroundColor: '#222',
        borderRadius: 12,
        padding: 10,
        margin: 5,
        alignItems: 'center',
        shadowColor: '#000',
        shadowOpacity: 0.2,
        shadowRadius: 5,
        elevation: 3,
    },
    passwordWebsite: {
        color: '#fff',
        fontWeight: 'bold',
        fontSize: 16,
        textAlign: 'center',
        marginBottom: 4,
    },
    passwordCategory: {
        color: '#bbb',
        fontSize: 14,
        textAlign: 'center',
    },
    passwordDate: {
        color: '#888',
        fontSize: 12,
        marginTop: 4,
        textAlign: 'center',
    },
    passwordEvaluation: {
        fontWeight: 'bold' as const,
        marginVertical: 4,
    }
});
