import { Dimensions, StyleSheet } from 'react-native';

const screenWidth = Dimensions.get('window').width;

export const styles = StyleSheet.create({
    scrollView: {
        flex: 1,
        backgroundColor: '#ffffffff',
    },
    scrollContent: {
        paddingTop: 100,
        flexGrow: 1,
        justifyContent: 'flex-start',
        alignItems: 'center',
    },
    container: {
        height: '100%',
        alignItems: 'flex-start',
        justifyContent: 'flex-start',
    },
    containerLeft: {
        height: '100%',
        alignItems: 'flex-start',
        justifyContent: 'flex-start',
    },
    text: {
        fontSize: 20,
        fontWeight: 'bold',
        margin: 10,
        color: 'black',
    },
    textWhite: {
        fontSize: 20,
        fontWeight: 'bold',
        margin: 10,
        color: 'white',
    },
    textBlack: {
        fontSize: 20,
        fontWeight: 'bold',
        marginTop: -10,
        marginLeft: -5,
        marginBottom: 5,
        color: 'black',
    },
    textWelcome: {
        fontSize: 20,
        fontWeight: 'bold',
        margin: 10,
        marginBottom: 2,
        color: 'white',
        textAlign: 'left',
    },
    textWelcomeSubtitle: {
        fontSize: 16,
        margin: 10,
        marginTop: 2,
        color: 'white',
        textAlign: 'left',
    },
    capsule: {
        width: screenWidth * 0.9,
        backgroundColor: '#000000ff',
        paddingVertical: 20,
        paddingHorizontal: screenWidth * 0.05,
        borderRadius:20,
        alignSelf: 'center',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.25,
        shadowRadius: 3.5,
        elevation: 5,
        alignItems: 'flex-start',
        paddingLeft: 5,
    },
    capsuleContainerCenter: {
        width: screenWidth * 1,
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingVertical: 20,
        paddingHorizontal: screenWidth * 0.05,
        borderRadius: 50,
        alignSelf: 'center',
    },
    capsuleCenter: {
        width: screenWidth * 0.9,
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingVertical: 20,
        paddingHorizontal: screenWidth * 0.05,
        borderRadius: 50,
        alignSelf: 'center',
        marginBottom: -30,
    },
    capsuleContainerLeft: {
        width: screenWidth * 1,
        flexDirection: 'column',
        justifyContent: 'space-between',
        paddingVertical: 20,
        paddingHorizontal: screenWidth * 0.05,
        borderRadius: 50,
        alignSelf: 'center',
    },
    capsuleChild: {
        width: screenWidth * 0.29,
        backgroundColor: '#000000ff',
        paddingVertical: 20,
        borderRadius: 20,
        alignItems: 'center',
        justifyContent: 'center',
        shadowColor: '#000000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.25,
        shadowRadius: 3.5,
        elevation: 5,
    },
    capsuleChildLeft: {
        width: screenWidth * 0.9 ,
        backgroundColor: '#000000ff',
        paddingVertical: 20,
        borderRadius: 20,
        paddingLeft: 20,
        marginBottom: 8,
        alignItems: 'flex-start',
        justifyContent: 'center',
        shadowColor: '#000000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.25,
        shadowRadius: 3.5,
        elevation: 5,
    },
    title: {
        fontSize: 22,
        fontWeight: 'bold',
        color: 'white',
        textAlign: 'center',
        marginTop: 8,
    },
    subtitle: {
        fontSize: 12,
        fontWeight: 'bold',
        color: 'white',
        textAlign: 'center',
        marginTop: 2,
    },
    safeArea: {
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        zIndex: 999,
        elevation: 10,
        backgroundColor: 'black',
        paddingTop: 0,
    },
    containerRibbon: {
        flexDirection: 'row',
        alignItems: 'center',
        marginTop: 40,
        marginBottom: 10,
        paddingVertical: 6,
        paddingHorizontal: 8,
    },
    iconShroud: {
        width: 48,
        height: 48,
        borderRadius: 16,
        backgroundColor: 'rgba(175, 173, 177, 0.2)',
        justifyContent: 'center',
        alignItems: 'center',
    },
    textStack: {
        flexDirection: 'column',
        justifyContent: 'center',
    },
    titleLeft: {
        fontSize: 22,
        fontWeight: 'bold',
        color: 'white',
        textAlign: 'left',
    },
    titleRibbon: {
        fontSize: 22,
        fontWeight: 'bold',
        color: 'black',
        textAlign: 'center',
    },
    subtitleRibbon: {
        fontSize: 16,
        fontWeight: 'bold',
        color: 'white',
        marginTop: 4,
    },
    subtitleBlack: {
        fontSize: 16,
        fontWeight: 'bold',
        color: 'black',
        marginTop: 4,
    },
    subtitleLeft: {
        fontSize: 16,
        fontWeight: 'bold',
        color: 'white',
        textAlign: 'left',
        marginTop: 4,
    },
    modalOverlay: {
        flex: 1,
        backgroundColor: 'rgba(0,0,0,0.5)',
        justifyContent: 'center',
        alignItems: 'center',
    },
    modalContent: {
        width: '80%',
        maxHeight: '80%',
        padding: 20,
        backgroundColor: 'white',
        borderRadius: 12,
        alignItems: 'center',
    },
    modalOverlayTouchableArea: {
        position: 'absolute',
        top: 0,
        bottom: 0,
        left: 0,
        right: 0,
    },
    image: {
        width: 150,
        height: 150,
        margin: 5,
        borderRadius: 10,
    },
    imagesContainer: {
        height: 300,
        marginTop: 20,
        borderWidth: 1,
        borderColor: '#ccc',
        borderRadius: 12,
    },
    imagesInnerContainer: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        justifyContent: 'center',
        gap: 10,
    },
    blackButton: {
        backgroundColor: 'black',
        paddingVertical: 12,
        paddingHorizontal: 24,
        borderRadius: 8,
        marginTop: 16,
        alignItems: 'center',
    },
    blackButtonText: {
        color: 'white',
        fontSize: 16,
        fontWeight: 'bold',
    },
});
